#ifndef STMMAC_H
#define STMMAC_H

#define REG32(addr) (*(volatile uint32_t *)(addr))

#define ETH_MAC_BASE_ADDR 0x40028000

// MAC-RELATED DEFINES

#define ETH_MACCR_OFFSET 0x0U
#define ETH_MACCR REG32(ETH_MAC_BASE_ADDR + ETH_MACCR_OFFSET)

#define ETH_MACFFR_OFFSET 0x4U
#define ETH_MACFFR REG32(ETH_MAC_BASE_ADDR + ETH_MACFFR_OFFSET)

#define ETH_MACHTHR_OFFSET 0X8U
#define ETH_MACHTHR REG32(ETH_MAC_BASE_ADDR + ETH_MACHTHR_OFFSET)

#define ETH_MACHTLR_OFFSET 0xCU
#define ETH_MACHTLR REG32(ETH_MAC_BASE_ADDR + ETH_MACHTLR_OFFSET)

#define ETH_MACMIIAR_OFFSET 0x10U
#define ETH_MACMIIAR REG32(ETH_MAC_BASE_ADDR + ETH_MACMIIAR_OFFSET)

#define ETH_MACMIIDR_OFFSET 0x14U
#define ETH_MACMIIDR REG32(ETH_MAC_BASE_ADDR + ETH_MACMIIDR_OFFSET)

#define ETH_MACFCR_OFFSET 0x18U
#define ETH_MACFCR REG32(ETH_MAC_BASE_ADDR + ETH_MACFCR_OFFSET)

#define ETH_MACVLANTR_OFFSET 0x1CU
#define ETH_MACVLANTR REG32(ETH_MAC_BASE_ADDR + ETH_MACVLANTR_OFFSET)

#define ETH_MACRWUFFR_OFFSET 0x28U
#define ETH_MACRWUFFR REG32(ETH_MAC_BASE_ADDR + ETH_MACRWUFFR_OFFSET)

#define ETH_MACPMTCSR_OFFSET 0x2CU
#define ETH_MACPMTCSR REG32(ETH_MAC_BASE_ADDR + ETH_MACPMTCSR_OFFSET)

#define ETH_MACDBGR_OFFSET 0x34U
#define ETH_MACDBGR REG32(ETH_MAC_BASE_ADDR + ETH_MACDBGR_OFFSET)

#define ETH_MACSR_OFFSET 0x38U
#define ETH_MACSR REG32(ETH_MAC_BASE_ADDR + ETH_MACSR_OFFSET)

#define ETH_MACIMR_OFFSET 0x3CU
#define ETH_MACIMR REG32(ETH_MAC_BASE_ADDR + ETH_MACIMR_OFFSET)

#define ETH_MACA0HR_OFFSET 0x40U
#define ETH_MACA0HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA0HR_OFFSET)

#define ETH_MACA0LR_OFFSET 0x44U
#define ETH_MACA0LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA0LR_OFFSET)

#define ETH_MACA1HR_OFFSET 0x48U
#define ETH_MACA1HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA1HR_OFFSET)

#define ETH_MACA1LR_OFFSET 0x4CU
#define ETH_MACA1LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA1LR_OFFSET)

#define ETH_MACA2HR_OFFSET 0x50U
#define ETH_MACA2HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA2HR_OFFSET)

#define ETH_MACA2LR_OFFSET 0x54U
#define ETH_MACA2LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA2LR_OFFSET)

#define ETH_MACA3HR_OFFSET 0x58U
#define ETH_MACA3HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA3HR_OFFSET)

#define ETH_MACA3LR_OFFSET 0x5CU
#define ETH_MACA3LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA3LR_OFFSET)

#define ETH_MMCCR_OFFSET 0x0100U
#define ETH_MMCCR REG32(ETH_MAC_BASE_ADDR + ETH_MMCCR_OFFSET)

#define ETH_MMCTIR_OFFSET 0x0108U
#define ETH_MMCTIR REG32(ETH_MAC_BASE_ADDR + ETH_MMCTIR_OFFSET)

#define ETH_MMCRIMR_OFFSET 0x010CU
#define ETH_MMCRIMR REG32(ETH_MAC_BASE_ADDR + ETH_MMCRIMR_OFFSET)

#define ETH_MMCTIMR_OFFSET 0X0110U
#define ETH_MMCTIMR REG32(ETH_MAC_BASE_ADDR + ETH_MMCTIMR)


// DMA-RELATED DEFINES
#define ETH_DMABMR_OFFSET 0x1000U
#define ETH_DMABMR REG32(ETH_MAC_BASE_ADDR + ETH_DMABMR_OFFSET)

#define ETH_DMATPDR_OFFSET 0x1004U
#define ETH_DMATPDR REG32(ETH_MAC_BASE_ADDR + ETH_DMATPDR_OFFSET)

#define ETH_DMARPDR_OFFSET 0x1008U
#define ETH_DMARPDR REG32(ETH_MAC_BASE_ADDR + ETH_DMARPDR_OFFSET)

#endif
