#ifndef STMMAC_H
#define STMMAC_H


// MAC-RELATED DEFINES
#define ETH_MACCR_OFFSET 0x0U
#define ETH_MACFFR_OFFSET 0x4U
#define ETH_MACHTHR_OFFSET 0X8U
#define ETH_MACHTLR_OFFSET 0xCU
#define ETH_MACMIIAR_OFFSET 0x10U
#define ETH_MACMIIDR_OFFSET 0x14U
#define ETH_MACFCR_OFFSET 0x18U
#define ETH_MACVLANTR_OFFSET 0x1CU
#define ETH_MACRWUFFR_OFFSET 0x28U
#define ETH_MACPMTCSR_OFFSET 0x2CU
#define ETH_MACDBGR_OFFSET 0x34U
#define ETH_MACSR_OFFSET 0x38U
#define ETH_MACIMR_OFFSET 0x3CU
#define ETH_MACA0HR_OFFSET 0x40U
#define ETH_MACA0LR_OFFSET 0x44U
#define ETH_MACA1HR_OFFSET 0x48U
#define ETH_MACA1LR_OFFSET 0x4CU
#define ETH_MACA2HR_OFFSET 0x50U
#define ETH_MACA2LR_OFFSET 0x54U
#define ETH_MACA3HR_OFFSET 0x58U
#define ETH_MACA3LR_OFFSET 0x5CU
#define ETH_MMCCR_OFFSET 0x0100U
#define ETH_MMCTIR_OFFSET 0x0108U
#define ETH_MMCRIMR_OFFSET 0x010CU
#define ETH_MMCTIMR_OFFSET 0X0110U


// DMA-RELATED DEFINES
#define ETH_DMABMR_OFFSET 0x1000U
#define ETH_DMATPDR_OFFSET 0x1004U
#define ETH_DMARPDR_OFFSET 0x1008U

#endif
