#ifndef STMMAC_H
#define STMMAC_H

#define REG32(addr) (*(volatile uint32_t *)(addr))

#define ETH_MAC_BASE_ADDR 0x40028000

// MAC-RELATED DEFINES

#define ETH_MACCR_OFFSET 0x0U
#define ETH_MACCR REG32(ETH_MAC_BASE_ADDR + ETH_MACCR_OFFSET)

#define ETH_MACCR_CSTF (1U << 25) // CRC stripping
#define ETH_MACCR_WD (1U << 23) // Watchdog disable
#define ETH_MACCR_JD (1U << 22) // Jabber disable
#define ETH_MACCR_IFG (1U << 17) // Interframe gap
#define ETH_MACCR_FES (1U << 14) // Fast ethernet speed
#define ETH_MACCR_ROD (1U << 13) // Recieve own disable
#define ETH_MACCR_LM (1U << 12) // Loopback Mode
#define ETH_MACCR_DM (1U << 11) // Duplex Mode
#define ETH_MACCR_IPCO (1U << 10) // IPv4 checksum offload
#define ETH_MACCR_RD (1U << 9) // Retry disable
#define ETH_MACCR_APCS (1U << 7) // Automatic Pad / CRC strip
#define ETH_MACCR_BL (1U << 5) // Back-off Limit
#define ETH_MACCR_DC (1U << 4) // Deferral Check
#define ETH_MACCR_TE (1U << 3) // Transmitter Enable
#define ETH_MACCR_RE (1U << 2) // Reciever Enable

#define ETH_MACFFR_OFFSET 0x4U
#define ETH_MACFFR REG32(ETH_MAC_BASE_ADDR + ETH_MACFFR_OFFSET)

#define ETH_MACFFR_RA (1U << 31) // Receive All
#define ETH_MACFFR_HPF (1U << 10) // Hash or Perfect filter
#define ETH_MACFFR_SAF (1U << 9) // Source address filter
#define ETH_MACFFR_SAIF (1U << 8) // Source address inverse filtering
#define ETH_MACFFR_PCF (1U << 6) // Pass control frames
#define ETH_MACFFR_BFD (1U << 5) // Broadcast frames disable
#define ETH_MACFFR_PAM (1U << 4) // Pass all multicast
#define ETH_MACFFR_DAIF (1U << 3) // Destination address inverse filtering
#define ETH_MACFFR_HM (1U << 2) // Hash multicast
#define ETH_MACFFR_HU (1U << 1) // Hash unicast
#define ETH_MACFFR_PM (1U << 0) // Promiscous Mode

#define ETH_MACHTHR_OFFSET 0X8U
#define ETH_MACHTHR REG32(ETH_MAC_BASE_ADDR + ETH_MACHTHR_OFFSET)

#define ETH_MACHTLR_OFFSET 0xCU
#define ETH_MACHTLR REG32(ETH_MAC_BASE_ADDR + ETH_MACHTLR_OFFSET)

#define ETH_MACMIIAR_OFFSET 0x10U
#define ETH_MACMIIAR REG32(ETH_MAC_BASE_ADDR + ETH_MACMIIAR_OFFSET)

#define ETH_MACMIIDR_OFFSET 0x14U
#define ETH_MACMIIDR REG32(ETH_MAC_BASE_ADDR + ETH_MACMIIDR_OFFSET)

#define ETH_MACFCR_OFFSET 0x18U
#define ETH_MACFCR REG32(ETH_MAC_BASE_ADDR + ETH_MACFCR_OFFSET)

#define ETH_MACVLANTR_OFFSET 0x1CU
#define ETH_MACVLANTR REG32(ETH_MAC_BASE_ADDR + ETH_MACVLANTR_OFFSET)

#define ETH_MACRWUFFR_OFFSET 0x28U
#define ETH_MACRWUFFR REG32(ETH_MAC_BASE_ADDR + ETH_MACRWUFFR_OFFSET)

#define ETH_MACPMTCSR_OFFSET 0x2CU
#define ETH_MACPMTCSR REG32(ETH_MAC_BASE_ADDR + ETH_MACPMTCSR_OFFSET)

#define ETH_MACDBGR_OFFSET 0x34U
#define ETH_MACDBGR REG32(ETH_MAC_BASE_ADDR + ETH_MACDBGR_OFFSET)

#define ETH_MACSR_OFFSET 0x38U
#define ETH_MACSR REG32(ETH_MAC_BASE_ADDR + ETH_MACSR_OFFSET)

#define ETH_MACIMR_OFFSET 0x3CU
#define ETH_MACIMR REG32(ETH_MAC_BASE_ADDR + ETH_MACIMR_OFFSET)

#define ETH_MACA0HR_OFFSET 0x40U
#define ETH_MACA0HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA0HR_OFFSET)

#define ETH_MACA0LR_OFFSET 0x44U
#define ETH_MACA0LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA0LR_OFFSET)

#define ETH_MACA1HR_OFFSET 0x48U
#define ETH_MACA1HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA1HR_OFFSET)

#define ETH_MACA1LR_OFFSET 0x4CU
#define ETH_MACA1LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA1LR_OFFSET)

#define ETH_MACA2HR_OFFSET 0x50U
#define ETH_MACA2HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA2HR_OFFSET)

#define ETH_MACA2LR_OFFSET 0x54U
#define ETH_MACA2LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA2LR_OFFSET)

#define ETH_MACA3HR_OFFSET 0x58U
#define ETH_MACA3HR REG32(ETH_MAC_BASE_ADDR + ETH_MACA3HR_OFFSET)

#define ETH_MACA3LR_OFFSET 0x5CU
#define ETH_MACA3LR REG32(ETH_MAC_BASE_ADDR + ETH_MACA3LR_OFFSET)

#define ETH_MMCCR_OFFSET 0x0100U
#define ETH_MMCCR REG32(ETH_MAC_BASE_ADDR + ETH_MMCCR_OFFSET)

#define ETH_MMCTIR_OFFSET 0x0108U
#define ETH_MMCTIR REG32(ETH_MAC_BASE_ADDR + ETH_MMCTIR_OFFSET)

#define ETH_MMCRIMR_OFFSET 0x010CU
#define ETH_MMCRIMR REG32(ETH_MAC_BASE_ADDR + ETH_MMCRIMR_OFFSET)

#define ETH_MMCTIMR_OFFSET 0X0110U
#define ETH_MMCTIMR REG32(ETH_MAC_BASE_ADDR + ETH_MMCTIMR)


// DMA-RELATED DEFINES
#define ETH_DMABMR_OFFSET 0x1000U
#define ETH_DMABMR REG32(ETH_MAC_BASE_ADDR + ETH_DMABMR_OFFSET)

#define ETH_DMATPDR_OFFSET 0x1004U
#define ETH_DMATPDR REG32(ETH_MAC_BASE_ADDR + ETH_DMATPDR_OFFSET)

#define ETH_DMARPDR_OFFSET 0x1008U
#define ETH_DMARPDR REG32(ETH_MAC_BASE_ADDR + ETH_DMARPDR_OFFSET)

// RCC-RELATED DEFINES
#define RCC_BASE_ADDR 0x40023800U

#define RCC_AHB1ENR_OFFSET 0x30U

#define RCC_AHB1ENR_ETHMACRXEN (1U << 27)
#define RCC_AHB1ENR_ETHMACTXEN (1U << 26)
#define RCC_AHB1ENR_ETHMACEN (1U << 25)

#endif
