
#include <string.h>

#include "ethernet.h"

#define DST_MAC_OFFSET_BYTES 0
#define DST_MAC_SIZE_BYTES 6

#define SRC_MAC_OFFSET_BYTES (DST_MAC_OFFSET_BYTES + DST_MAC_SIZE_BYTES)
#define SRC_MAC_SIZE_BYTES 6

#define ETHERTYPE_OFFSET_BYTES (SRC_MAC_OFFSET_BYTES + SRC_MAC_SIZE_BYTES)
#define ETHERTYPE_SIZE_BYTES 2

#define ETH_HEADER_LEN (DST_MAC_SIZE_BYTES + SRC_MAC_SIZE_BYTES + ETHERTYPE_SIZE_BYTES)

static inline void add_dst(uint8_t *hdr, const uint8_t *dst);

static inline void add_src(uint8_t *hdr, const uint8_t *src);

static inline void add_ethertype(uint8_t *hdr, const uint16_t len);

bool ethernet_add_header(const ethernet_header_t *eth_header, netbuf_t *nb)
{
    if (!eth_header || !nb)
    {
        return false;
    }

    // the ethernet fcs may need to be added here, but may also be auto generated by the hardware
    
    uint8_t e_hdr[ETH_HEADER_LEN];

    add_dst(e_hdr, eth_header->dst_mac);
    add_src(e_hdr, eth_header->src_mac);
    add_ethertype(e_hdr, (uint16_t) eth_header->ethertype);

    return netbuf_push(nb, e_hdr, ETH_HEADER_LEN);
}

static inline void add_dst(uint8_t *hdr, const uint8_t *dst)
{
    memcpy(hdr + DST_MAC_OFFSET_BYTES, dst, DST_MAC_SIZE_BYTES);
}

static inline void add_src(uint8_t *hdr, const uint8_t *src)
{
    memcpy(hdr + SRC_MAC_OFFSET_BYTES, src, SRC_MAC_SIZE_BYTES);
}

static inline void add_ethertype(uint8_t *hdr, const uint16_t len)
{
    memcpy(hdr + ETHERTYPE_OFFSET_BYTES, len, ETHERTYPE_SIZE_BYTES);
}

