/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32l4xx.h>

#define SYSTICK_HZ 2

void delay(volatile uint32_t count) {
    while (count--) {
        __NOP();
    }
}

typedef enum state {
	BUSY,
	IDLE
} state;

typedef struct process {
	void *sp; // stack pointer
	state proc_state;
};

void init_systick(int hz)
{
	SysTick->CTRL &= ~0x01;

	SysTick->LOAD = (4000000/hz)-1;

	SysTick->VAL &= ~0xFFF; // clear value reg

	SysTick->CTRL |= 0x04; // processor clock
	SysTick->CTRL |= 0x02; // enable exception

	SysTick->CTRL |= 0x01; //enable systick
}

void SysTick_Handler(void)
{
	GPIOA->ODR ^= (1U << 5);
}

int main(void)
{
    // 1. Enable clock for GPIOA
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;

    // Small delay after enabling clock (recommended)
    __NOP(); __NOP();

    // 2. Set PA5 as output (MODER5 = 01)
    GPIOA->MODER &= ~(3U << (5 * 2));   // clear bits
    GPIOA->MODER |=  (1U << (5 * 2));   // set as output

    // 3. Optional: push-pull (default), no pull-up/down
    GPIOA->OTYPER &= ~(1U << 5);
    GPIOA->PUPDR  &= ~(3U << (5 * 2));

    init_systick(2);

    while (1)
    {
    }
}
